apiVersion: v1
kind: Service
metadata:
  name: chat-system-app
  namespace: chat-system
  labels:
    app: chat-system-app
spec:
  selector:
    app: chat-system-app
  ports:
    - port: 80
      targetPort: 3000
