apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-system-mongo
  namespace: chat-system
  labels:
    app: chat-system-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-system-mongo
  template:
    metadata:
      labels:
        app: chat-system-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-system-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-system-secret
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: chat
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: chat-system-mongo-pvc
