apiVersion: v1
kind: Secret
metadata:
  name: chat-system-secret
  namespace: chat-system
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "change-me"
  MONGODB_URI: "mongodb://admin:change-me@chat-system-mongo:27017/chat?authSource=admin"
  JWT_SECRET: "change-me"
